// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: VEIv1_0.proto

package VEIv1_0

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubImageParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraID  string `protobuf:"bytes,1,opt,name=cameraID,proto3" json:"cameraID,omitempty"`
	Image     []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PubImageParams) Reset() {
	*x = PubImageParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubImageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubImageParams) ProtoMessage() {}

func (x *PubImageParams) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubImageParams.ProtoReflect.Descriptor instead.
func (*PubImageParams) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{0}
}

func (x *PubImageParams) GetCameraID() string {
	if x != nil {
		return x.CameraID
	}
	return ""
}

func (x *PubImageParams) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *PubImageParams) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SubImageParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraID string `protobuf:"bytes,1,opt,name=cameraID,proto3" json:"cameraID,omitempty"`
}

func (x *SubImageParams) Reset() {
	*x = SubImageParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubImageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubImageParams) ProtoMessage() {}

func (x *SubImageParams) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubImageParams.ProtoReflect.Descriptor instead.
func (*SubImageParams) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{1}
}

func (x *SubImageParams) GetCameraID() string {
	if x != nil {
		return x.CameraID
	}
	return ""
}

type ImageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error     string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{2}
}

func (x *ImageData) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ImageData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CameraID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraID string `protobuf:"bytes,1,opt,name=cameraID,proto3" json:"cameraID,omitempty"`
}

func (x *CameraID) Reset() {
	*x = CameraID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraID) ProtoMessage() {}

func (x *CameraID) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraID.ProtoReflect.Descriptor instead.
func (*CameraID) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{3}
}

func (x *CameraID) GetCameraID() string {
	if x != nil {
		return x.CameraID
	}
	return ""
}

type PubVisionParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisionAppName string   `protobuf:"bytes,1,opt,name=visionAppName,proto3" json:"visionAppName,omitempty"`
	VisionOutput  []string `protobuf:"bytes,2,rep,name=visionOutput,proto3" json:"visionOutput,omitempty"`
	Timestamp     string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PubVisionParams) Reset() {
	*x = PubVisionParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubVisionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubVisionParams) ProtoMessage() {}

func (x *PubVisionParams) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubVisionParams.ProtoReflect.Descriptor instead.
func (*PubVisionParams) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{4}
}

func (x *PubVisionParams) GetVisionAppName() string {
	if x != nil {
		return x.VisionAppName
	}
	return ""
}

func (x *PubVisionParams) GetVisionOutput() []string {
	if x != nil {
		return x.VisionOutput
	}
	return nil
}

func (x *PubVisionParams) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SubVisionParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisionAppName string `protobuf:"bytes,1,opt,name=visionAppName,proto3" json:"visionAppName,omitempty"`
}

func (x *SubVisionParams) Reset() {
	*x = SubVisionParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubVisionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubVisionParams) ProtoMessage() {}

func (x *SubVisionParams) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubVisionParams.ProtoReflect.Descriptor instead.
func (*SubVisionParams) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{5}
}

func (x *SubVisionParams) GetVisionAppName() string {
	if x != nil {
		return x.VisionAppName
	}
	return ""
}

type VisionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisionOutput []string `protobuf:"bytes,1,rep,name=visionOutput,proto3" json:"visionOutput,omitempty"`
	Timestamp    string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error        string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VisionOutput) Reset() {
	*x = VisionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisionOutput) ProtoMessage() {}

func (x *VisionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisionOutput.ProtoReflect.Descriptor instead.
func (*VisionOutput) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{6}
}

func (x *VisionOutput) GetVisionOutput() []string {
	if x != nil {
		return x.VisionOutput
	}
	return nil
}

func (x *VisionOutput) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *VisionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PubCloudParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnalyticsName    string   `protobuf:"bytes,1,opt,name=analyticsName,proto3" json:"analyticsName,omitempty"`
	AnalyticalOutput []string `protobuf:"bytes,2,rep,name=analyticalOutput,proto3" json:"analyticalOutput,omitempty"`
	Timestamp        string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CloudProvider    string   `protobuf:"bytes,4,opt,name=cloudProvider,proto3" json:"cloudProvider,omitempty"`
}

func (x *PubCloudParams) Reset() {
	*x = PubCloudParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubCloudParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubCloudParams) ProtoMessage() {}

func (x *PubCloudParams) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubCloudParams.ProtoReflect.Descriptor instead.
func (*PubCloudParams) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{7}
}

func (x *PubCloudParams) GetAnalyticsName() string {
	if x != nil {
		return x.AnalyticsName
	}
	return ""
}

func (x *PubCloudParams) GetAnalyticalOutput() []string {
	if x != nil {
		return x.AnalyticalOutput
	}
	return nil
}

func (x *PubCloudParams) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PubCloudParams) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMsg string `protobuf:"bytes,1,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type Cameras struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableCams []string `protobuf:"bytes,1,rep,name=availableCams,proto3" json:"availableCams,omitempty"`
}

func (x *Cameras) Reset() {
	*x = Cameras{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cameras) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cameras) ProtoMessage() {}

func (x *Cameras) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cameras.ProtoReflect.Descriptor instead.
func (*Cameras) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{9}
}

func (x *Cameras) GetAvailableCams() []string {
	if x != nil {
		return x.AvailableCams
	}
	return nil
}

type Applications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailApps []string `protobuf:"bytes,1,rep,name=availApps,proto3" json:"availApps,omitempty"`
}

func (x *Applications) Reset() {
	*x = Applications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Applications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Applications) ProtoMessage() {}

func (x *Applications) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Applications.ProtoReflect.Descriptor instead.
func (*Applications) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{10}
}

func (x *Applications) GetAvailApps() []string {
	if x != nil {
		return x.AvailApps
	}
	return nil
}

type Clouds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailClouds []string `protobuf:"bytes,1,rep,name=availClouds,proto3" json:"availClouds,omitempty"`
}

func (x *Clouds) Reset() {
	*x = Clouds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VEIv1_0_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clouds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clouds) ProtoMessage() {}

func (x *Clouds) ProtoReflect() protoreflect.Message {
	mi := &file_VEIv1_0_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clouds.ProtoReflect.Descriptor instead.
func (*Clouds) Descriptor() ([]byte, []int) {
	return file_VEIv1_0_proto_rawDescGZIP(), []int{11}
}

func (x *Clouds) GetAvailClouds() []string {
	if x != nil {
		return x.AvailClouds
	}
	return nil
}

var File_VEIv1_0_proto protoreflect.FileDescriptor

var file_VEIv1_0_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2c, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x49, 0x44, 0x22, 0x55, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x08,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x49, 0x44, 0x22, 0x79, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x56, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x37, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x0c, 0x56, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0xa6, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0d, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x73, 0x22, 0x2c, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x41, 0x70, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x41, 0x70, 0x70, 0x73, 0x22, 0x2a, 0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x73, 0x32, 0xe9, 0x04, 0x0a, 0x07, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x12, 0x43, 0x0a,
	0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e,
	0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x50, 0x75, 0x62, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x41, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x53,
	0x75, 0x62, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x12, 0x2e,
	0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x11, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31,
	0x5f, 0x30, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x56, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x2e, 0x56, 0x45, 0x49, 0x76,
	0x31, 0x5f, 0x30, 0x2e, 0x50, 0x75, 0x62, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x4c, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31,
	0x5f, 0x30, 0x2e, 0x53, 0x75, 0x62, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x15, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x56, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a,
	0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x12,
	0x17, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x50, 0x75, 0x62, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e, 0x56, 0x45, 0x49, 0x76, 0x31,
	0x5f, 0x30, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x39, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x56, 0x45,
	0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x56, 0x45,
	0x49, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x56, 0x45, 0x49,
	0x76, 0x31, 0x5f, 0x30, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2f, 0x56, 0x45, 0x49, 0x76, 0x31, 0x5f, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_VEIv1_0_proto_rawDescOnce sync.Once
	file_VEIv1_0_proto_rawDescData = file_VEIv1_0_proto_rawDesc
)

func file_VEIv1_0_proto_rawDescGZIP() []byte {
	file_VEIv1_0_proto_rawDescOnce.Do(func() {
		file_VEIv1_0_proto_rawDescData = protoimpl.X.CompressGZIP(file_VEIv1_0_proto_rawDescData)
	})
	return file_VEIv1_0_proto_rawDescData
}

var file_VEIv1_0_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_VEIv1_0_proto_goTypes = []interface{}{
	(*PubImageParams)(nil),  // 0: VEIv1_0.PubImageParams
	(*SubImageParams)(nil),  // 1: VEIv1_0.SubImageParams
	(*ImageData)(nil),       // 2: VEIv1_0.ImageData
	(*CameraID)(nil),        // 3: VEIv1_0.CameraID
	(*PubVisionParams)(nil), // 4: VEIv1_0.PubVisionParams
	(*SubVisionParams)(nil), // 5: VEIv1_0.SubVisionParams
	(*VisionOutput)(nil),    // 6: VEIv1_0.VisionOutput
	(*PubCloudParams)(nil),  // 7: VEIv1_0.PubCloudParams
	(*ErrorResponse)(nil),   // 8: VEIv1_0.ErrorResponse
	(*Cameras)(nil),         // 9: VEIv1_0.Cameras
	(*Applications)(nil),    // 10: VEIv1_0.Applications
	(*Clouds)(nil),          // 11: VEIv1_0.Clouds
	(*empty.Empty)(nil),     // 12: google.protobuf.Empty
}
var file_VEIv1_0_proto_depIdxs = []int32{
	0,  // 0: VEIv1_0.VEIv1_0.PublishImage:input_type -> VEIv1_0.PubImageParams
	1,  // 1: VEIv1_0.VEIv1_0.SubscribeImage:input_type -> VEIv1_0.SubImageParams
	3,  // 2: VEIv1_0.VEIv1_0.DeleteCamera:input_type -> VEIv1_0.CameraID
	4,  // 3: VEIv1_0.VEIv1_0.PublishVisionOutput:input_type -> VEIv1_0.PubVisionParams
	5,  // 4: VEIv1_0.VEIv1_0.SubscribeVisionOutput:input_type -> VEIv1_0.SubVisionParams
	7,  // 5: VEIv1_0.VEIv1_0.PublishToCloud:input_type -> VEIv1_0.PubCloudParams
	12, // 6: VEIv1_0.VEIv1_0.ListCameras:input_type -> google.protobuf.Empty
	12, // 7: VEIv1_0.VEIv1_0.ListApplications:input_type -> google.protobuf.Empty
	12, // 8: VEIv1_0.VEIv1_0.ListClouds:input_type -> google.protobuf.Empty
	8,  // 9: VEIv1_0.VEIv1_0.PublishImage:output_type -> VEIv1_0.ErrorResponse
	2,  // 10: VEIv1_0.VEIv1_0.SubscribeImage:output_type -> VEIv1_0.ImageData
	8,  // 11: VEIv1_0.VEIv1_0.DeleteCamera:output_type -> VEIv1_0.ErrorResponse
	8,  // 12: VEIv1_0.VEIv1_0.PublishVisionOutput:output_type -> VEIv1_0.ErrorResponse
	6,  // 13: VEIv1_0.VEIv1_0.SubscribeVisionOutput:output_type -> VEIv1_0.VisionOutput
	8,  // 14: VEIv1_0.VEIv1_0.PublishToCloud:output_type -> VEIv1_0.ErrorResponse
	9,  // 15: VEIv1_0.VEIv1_0.ListCameras:output_type -> VEIv1_0.Cameras
	10, // 16: VEIv1_0.VEIv1_0.ListApplications:output_type -> VEIv1_0.Applications
	11, // 17: VEIv1_0.VEIv1_0.ListClouds:output_type -> VEIv1_0.Clouds
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_VEIv1_0_proto_init() }
func file_VEIv1_0_proto_init() {
	if File_VEIv1_0_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_VEIv1_0_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubImageParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubImageParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubVisionParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubVisionParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubCloudParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cameras); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Applications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VEIv1_0_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clouds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_VEIv1_0_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_VEIv1_0_proto_goTypes,
		DependencyIndexes: file_VEIv1_0_proto_depIdxs,
		MessageInfos:      file_VEIv1_0_proto_msgTypes,
	}.Build()
	File_VEIv1_0_proto = out.File
	file_VEIv1_0_proto_rawDesc = nil
	file_VEIv1_0_proto_goTypes = nil
	file_VEIv1_0_proto_depIdxs = nil
}
